apiVersion: v1
kind: Pod
metadata:
  name: nodejs-api-quickstart-pod
  labels:
    app: nodejs-api-quickstart
spec:
  containers:
  - name: nodejs-api-quickstart-container
    image: agilite/nodejs-api-quickstart
    ports:
    - containerPort: 3000