apiVersion: v1
kind: Service
metadata:
  name: agilite-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 30010
    targetPort: a-api-port
    protocol: TCP
  selector:
    app: agilite-api-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: agilite-api-server-deployment
spec:
  selector:
    matchLabels:
      app: agilite-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-api-server
        version: v523-4
    spec:
      containers:
      - name: agilite-api-server-523-4
        image: acragilitedemo.azurecr.io/agilite-api-server-docker:v5.2.3-4
        imagePullPolicy: IfNotPresent
        ports:
        - name: a-api-port
          containerPort: 6010