apiVersion: v1
kind: Service
metadata:
  name: agilite-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 30010
    targetPort: a-api-port
    protocol: TCP
  selector:
    app: agilite-api-server