apiVersion: v1
kind: Service
metadata:
  name: agilite-api-service
spec:
  ports:
  - port: 30010
    nodePort: 30010
    targetPort: a-api-port
    protocol: TCP
  selector:
    app: agilite-api-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: agilite-admin-service
spec:
  ports:
  - port: 30013
    nodePort: 30013
    targetPort: a-admin-port
    protocol: TCP
  selector:
    app: agilite-admin-portal
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilite-api-server-deployment
spec:
  selector:
    matchLabels:
      app: agilite-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-api-server
        version: v522
    spec:
      containers:
      - name: agilite-api-server-522
        image: agilite/agilite-api-server-docker:5.2.2
        imagePullPolicy: Never
        ports:
        - name: a-api-port
          containerPort: 6010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilite-admin-portal-deployment
spec:
  selector:
    matchLabels:
      app: agilite-admin-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-admin-portal
        version: v522
    spec:
      containers:
      - name: agilite-admin-portal-522
        image: agilite/agilite-admin-portal-docker:5.2.2
        imagePullPolicy: Never
        ports:
        - name: a-admin-port
          containerPort: 6013