apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: agilite-admin-portal-deployment
spec:
  selector:
    matchLabels:
      app: agilite-admin-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-admin-portal
        version: v542
    spec:
      containers:
      - name: agilite-admin-portal-542
        image: acragilitedemo.azurecr.io/agilite-admin-portal-docker:v5.4.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: a-admin-port
          containerPort: 6013