apiVersion: v1
kind: Service
metadata:
  name: agilite-admin-service
spec:
  type: LoadBalancer
  ports:
  - port: 30013
    targetPort: a-admin-port
    protocol: TCP
  selector:
    app: agilite-admin-portal