apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: agilite-api-server-deployment
spec:
  selector:
    matchLabels:
      app: agilite-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-api-server
        version: v530-1
    spec:
      containers:
      - name: agilite-api-server-530-1
        image: acragilitedemo.azurecr.io/agilite-api-server-docker:v5.3.0-1
        imagePullPolicy: IfNotPresent
        ports:
        - name: a-api-port
          containerPort: 6010