apiVersion: v1
kind: Service
metadata:
  name: botbuilder-service
spec:
  ports:
  - port: 30022
    name: http
    targetPort: botbuilder-port
    protocol: TCP
  selector:
    app: botbuilder-docker