apiVersion: v1
kind: Service
metadata:
  name: anrd-service
spec:
  ports:
  - port: 30011
    nodePort: 30011
    targetPort: anrd-port
    protocol: TCP
  selector:
    app: agilite-node-red-docker
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: agilite-api-service
spec:
  ports:
  - port: 30010
    nodePort: 30010
    targetPort: a-api-port
    protocol: TCP
  selector:
    app: agilite-api-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: agilite-admin-service
spec:
  ports:
  - port: 30013
    nodePort: 30013
    targetPort: a-admin-port
    protocol: TCP
  selector:
    app: agilite-admin-portal
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anrd-deployment
spec:
  selector:
    matchLabels:
      app: agilite-node-red-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-node-red-docker
        version: v001
    spec:
      containers:
      - name: anrd-001
        image: agilite/node-red-docker:0.0.1
        imagePullPolicy: Never
        ports:
        - name: anrd-port
          containerPort: 6011
        volumeMounts:
          - name: anrd-storage
            mountPath: /app/flows/
          - name: anrd-config-volume
            mountPath: /app/config.json
      volumes:
        - name: anrd-storage
          persistentVolumeClaim:
            claimName: anrd-pvc
        - name: anrd-config-volume
          configMap:
            name: anrd-config
            items:
            - key: config.json
              path: config.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilite-api-server-deployment
spec:
  selector:
    matchLabels:
      app: agilite-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-api-server
        version: v522
    spec:
      containers:
      - name: agilite-api-server-522
        image: agilite/agilite-api-server:5.2.2
        imagePullPolicy: Never
        ports:
        - name: a-api-port
          containerPort: 6010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilite-admin-portal-deployment
spec:
  selector:
    matchLabels:
      app: agilite-admin-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-admin-portal
        version: v522
    spec:
      containers:
      - name: agilite-admin-portal-522
        image: agilite/agilite-admin-portal:5.2.2
        imagePullPolicy: Never
        ports:
        - name: a-admin-port
          containerPort: 6013      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anrd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: anr-egress-rule
spec:
  destination:
    service: agilite-node-red.eu-gb.mybluemix.net
  ports:
    - port: 80
      protocol: http
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: mongo-egress-rule
spec:
  destination:
    service: localhost
  ports:
    - port: 27017
      protocol: mongo