apiVersion: v1
kind: Service
metadata:
  name: anrd-service
spec:
  ports:
  - port: 30050
    nodePort: 30050
    targetPort: anrd-port
    protocol: TCP
  selector:
    app: agilite-node-red-docker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anrd-deployment
spec:
  selector:
    matchLabels:
      app: agilite-node-red-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-node-red-docker
        version: v012
    spec:
      containers:
      - name: anrd-012
        image: agilite/node-red-docker:0.1.2
        imagePullPolicy: Never
        ports:
        - name: anrd-port
          containerPort: 6050
        volumeMounts:
          - name: anrd-storage
            mountPath: /app/flows/
          - name: anrd-config-volume
            mountPath: /app/config.json
      volumes:
        - name: anrd-storage
          persistentVolumeClaim:
            claimName: anrd-pvc
        - name: anrd-config-volume
          configMap:
            name: anrd-config
            items:
            - key: config.json
              path: config.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anrd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: anr-egress-rule
spec:
  destination:
    service: agilite-node-red.eu-gb.mybluemix.net
  ports:
    - port: 80
      protocol: http