apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: LoadBalancer
  ports:
  - port: 30017
    targetPort: mongo-port
  selector:
    app: mongo-db
---  
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
        version: v34
    spec:
      containers:
      - name: mongo-34
        image: acragilitetest.azurecr.io/mongo:v3.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi