apiVersion: v1
kind: Service
metadata:
  name: anrd-service
spec:
  type: LoadBalancer
  ports:
  - port: 30011
    targetPort: anrd-port
    protocol: TCP
  selector:
    app: agilite-node-red-docker