apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: anrd-deployment
spec:
  selector:
    matchLabels:
      app: agilite-node-red-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-node-red-docker
        version: v006
    spec:
      containers:
      - name: anrd-006
        image: acragilitedemo.azurecr.io/agilite-node-red-docker:v0.0.6
        imagePullPolicy: IfNotPresent
        ports:
        - name: anrd-port
          containerPort: 6011
        volumeMounts:
          - name: anrd-storage
            mountPath: /app/flows/
          - name: anrd-config-volume
            mountPath: /app/config.json
      volumes:
        - name: anrd-storage
          persistentVolumeClaim:
            claimName: anrd-pvc
        - name: anrd-config-volume
          configMap:
            name: anrd-config
            items:
            - key: anrd-config.json
              path: config.json