apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: react-to-do-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: react-to-do-docker
        version: v007
    spec:
      containers:
      - name: todo-007
        image: acragilitedemo.azurecr.io/react-to-do-docker:v0.0.7
        imagePullPolicy: IfNotPresent
        ports:
        - name: todo-port
          containerPort: 6020