apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: react-to-do-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: react-to-do-docker
        version: v005-1
    spec:
      containers:
      - name: todo-005-1
        image: acragilitedemo.azurecr.io/react-to-do-docker:v0.0.5-1
        imagePullPolicy: IfNotPresent
        ports:
        - name: todo-port
          containerPort: 6020