apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  ports:
  - port: 30020
    nodePort: 30020
    targetPort: todo-port
    protocol: TCP
  selector:
    app: react-to-do-docker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: react-to-do-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: react-to-do-docker
        version: v001
    spec:
      containers:
      - name: todo-001
        image: agilite/react-to-do-docker:0.0.1
        imagePullPolicy: Never
        ports:
        - name: todo-port
          containerPort: 6020