apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  ports:
  - port: 30020
    name: http
    targetPort: todo-port
    protocol: TCP
  selector:
    app: react-to-do-docker