apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  ports:
  - port: 30020
    name: http
    targetPort: todo-port
    protocol: TCP
  selector:
    app: react-to-do-docker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: react-to-do-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: react-to-do-docker
        version: v004
    spec:
      containers:
      - name: todo-004
        image: acragilitetest.azurecr.io/react-to-do-docker:v0.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: todo-port
          containerPort: 6020