apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  type: LoadBalancer
  ports:
  - port: 30021
    name: http
    targetPort: ws-port
    protocol: TCP
  selector:
    app: web-socket-server-docker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  selector:
    matchLabels:
      app: web-socket-server-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: web-socket-server-docker
        version: v002
    spec:
      containers:
      - name: ws-002
        image: acragilitetest.azurecr.io/web-socket-server-docker:v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: ws-port
          containerPort: 6021
        volumeMounts:
          - name: ws-config-volume
            mountPath: /app/config.json
      volumes:
        - name: ws-config-volume
          configMap:
            name: ws-config
            items:
            - key: ws-config.json
              path: config.json