apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  ports:
  - port: 30021
    name: http
    nodePort: 30021
    targetPort: ws-port
    protocol: TCP
  selector:
    app: web-socket-server-docker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  selector:
    matchLabels:
      app: web-socket-server-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: web-socket-server-docker
        version: v003
    spec:
      containers:
      - name: ws-003
        image: agilite/web-socket-server-docker:0.0.3
        imagePullPolicy: Never
        ports:
        - name: ws-port
          containerPort: 6021
        volumeMounts:
          - name: ws-config-volume
            mountPath: /app/config.json
      volumes:
        - name: ws-config-volume
          configMap:
            name: ws-config
            items:
            - key: ws-config.json
              path: config.json