apiVersion: v1
kind: Service
metadata:
  name: anrd-service
spec:
  ports:
  - port: 30050
    nodePort: 30050
    targetPort: anrd-port
    protocol: TCP
  selector:
    app: agilite-node-red-docker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anrd-deployment
spec:
  selector:
    matchLabels:
      app: agilite-node-red-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: agilite-node-red-docker
        version: v004
    spec:
      containers:
      - name: anrd-004
        image: agilite/node-red-docker:0.0.4
        imagePullPolicy: Never
        ports:
        - name: anrd-port
          containerPort: 6050
        volumeMounts:
          - name: anrd-storage
            mountPath: /app/flows/
      volumes:
        - name: anrd-storage
          persistentVolumeClaim:
            claimName: anrd-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anrd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M